<a href="https://colab.research.google.com/github/jeguns/Manipulacion-de-datos-con-R-y-Python/blob/main/Python/9%20-%20Manipulaci%C3%B3n%20de%20datos/U9_Manipulaci%C3%B3n_de_datos_en_Python_P1%20-%20Codigos%20en%20clase.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

## Lectura

El archivo U9 - DATOS1.xlsx corresponde a la [ENDES 2022](https://www.datosabiertos.gob.pe/dataset/encuesta-demogr%C3%A1fica-y-de-salud-familiar-endes-2022-instituto-nacional-de-estad%C3%ADstica-e).

In [1]:
import pandas as pd
datos = pd.read_excel('U9 - DATOS1.xlsx')
datos.head(10)

,ID1,HHID,HV000,HV001,HV002,HV002A,HV003,HV004,HV007,HV008,...,HV043,HV044,UBIGEO,HV005,HV022,NCONGLOME,CODCCPP,NOMCCPP,LONGITUDX,LATITUDY
0,2022,101701,PE6,1,17,1,2,1,2022,1467,...,0,1,10101,599332,3,706402,1,CHACHAPOYAS,-77.87403,-6.221249
1,2022,102201,PE6,1,22,1,2,1,2022,1467,...,0,1,10101,96698,3,706402,1,CHACHAPOYAS,-77.87403,-6.221249
2,2022,105201,PE6,1,52,1,3,1,2022,1467,...,0,1,10101,96698,3,706402,1,CHACHAPOYAS,-77.87403,-6.221249
3,2022,105301,PE6,1,53,1,1,1,2022,1467,...,0,1,10101,96698,3,706402,1,CHACHAPOYAS,-77.87403,-6.221249
4,2022,105501,PE6,1,55,1,1,1,2022,1467,...,0,1,10101,599332,3,706402,1,CHACHAPOYAS,-77.87403,-6.221249
5,2022,108301,PE6,1,83,1,2,1,2022,1467,...,0,1,10101,599332,3,706402,1,CHACHAPOYAS,-77.87403,-6.221249
6,2022,108501,PE6,1,85,1,2,1,2022,1467,...,0,1,10101,96698,3,706402,1,CHACHAPOYAS,-77.87403,-6.221249
7,2022,109501,PE6,1,95,1,0,1,2022,1467,...,0,1,10101,0,3,706402,1,CHACHAPOYAS,-77.87403,-6.221249
8,2022,110301,PE6,1,103,1,2,1,2022,1467,...,0,1,10101,96698,3,706402,1,CHACHAPOYAS,-77.87403,-6.221249
9,2022,110701,PE6,1,107,1,2,1,2022,1467,...,0,1,10101,96698,3,706402,1,CHACHAPOYAS,-77.87403,-6.221249

## Selección de variables

In [11]:
# Una lista de las variables a seleccionar dentro de corchetes
datos01 = datos[['HV009', 'HV010', 'HV014', 'HV015', 'HV024', 'HV025', 'HV035', 'HV042', 'NOMCCPP', 'LONGITUDX', 'LATITUDY']]
datos01

,HV009,HV010,HV014,HV015,HV024,HV025,HV035,HV042,NOMCCPP,LONGITUDX,LATITUDY
0,4,0,0,1,1,1,0,1,CHACHAPOYAS,-77.874030,-6.221249
1,3,1,1,1,1,1,1,1,CHACHAPOYAS,-77.874030,-6.221249
2,5,3,1,1,1,1,1,1,CHACHAPOYAS,-77.874030,-6.221249
3,4,2,1,1,1,1,1,1,CHACHAPOYAS,-77.874030,-6.221249
4,2,0,0,1,1,1,0,1,CHACHAPOYAS,-77.874030,-6.221249
...,...,...,...,...,...,...,...,...,...,...,...
37345,0,0,0,5,15,1,0,1,SAN MIGUEL,-77.079472,-12.090833
37346,0,0,0,5,15,1,0,1,SAN MIGUEL,-77.079472,-12.090833
37347,3,1,1,1,15,1,1,1,SAN MIGUEL,-77.079472,-12.090833
37348,0,0,0,5,15,1,0,1,SAN MIGUEL,-77.079472,-12.090833
37349,0,0,0,5,15,1,0,1,SAN MIGUEL,-77.079472,-12.090833

In [3]:
# Usando loc: indicamos una lista de nombres de variables
datos02 = datos.loc[:, ['HV009', 'HV010', 'HV014', 'HV015', 'HV024', 'HV025', 'HV035', 'HV042', 'NOMCCPP', 'LONGITUDX', 'LATITUDY']]

In [4]:
# Usando iloc: indicamos una lista de posiciones de variables
datos03 = datos.iloc[:, [10, 11, 15, 16, 21, 22, 30, 33] + list(range(41, 44))]
# datos03 = datos.iloc[:, [10, 11, 15, 16, 21, 22, 30, 33, 41, 42, 43]]

In [5]:
datos01.equals(datos02)

True

In [6]:
datos02.equals(datos03)

True

In [16]:
# Elimina las columnas que se indica como lista
datos04 = datos.drop(columns=['ID1', 'HHID', 'HV000'])
datos04

,HV001,HV002,HV002A,HV003,HV004,HV007,HV008,HV009,HV010,HV011,...,HV043,HV044,UBIGEO,HV005,HV022,NCONGLOME,CODCCPP,NOMCCPP,LONGITUDX,LATITUDY
0,1,17,1,2,1,2022,1467,4,0,0,...,0,1,10101,599332,3,706402,1,CHACHAPOYAS,-77.874030,-6.221249
1,1,22,1,2,1,2022,1467,3,1,0,...,0,1,10101,96698,3,706402,1,CHACHAPOYAS,-77.874030,-6.221249
2,1,52,1,3,1,2022,1467,5,3,0,...,0,1,10101,96698,3,706402,1,CHACHAPOYAS,-77.874030,-6.221249
3,1,53,1,1,1,2022,1467,4,2,0,...,0,1,10101,96698,3,706402,1,CHACHAPOYAS,-77.874030,-6.221249
4,1,55,1,1,1,2022,1467,2,0,0,...,0,1,10101,599332,3,706402,1,CHACHAPOYAS,-77.874030,-6.221249
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
37345,4343,149,1,0,4343,2022,1474,0,0,0,...,0,1,150136,0,139,25531,1,SAN MIGUEL,-77.079472,-12.090833
37346,4343,153,1,0,4343,2022,1474,0,0,0,...,0,1,150136,0,139,25531,1,SAN MIGUEL,-77.079472,-12.090833
37347,4343,161,1,1,4343,2022,1474,3,1,0,...,0,1,150136,1081900,139,25531,1,SAN MIGUEL,-77.079472,-12.090833
37348,4343,177,1,0,4343,2022,1474,0,0,0,...,0,1,150136,0,139,25531,1,SAN MIGUEL,-77.079472,-12.090833
37349,4343,204,1,0,4343,2022,1474,0,0,0,...,0,1,150136,0,139,25531,1,SAN MIGUEL,-77.079472,-12.090833

In [8]:
datos05 = datos.iloc[:, 3:]

In [9]:
datos04.equals(datos05)

True

In [10]:
datos06 = datos[['HV014']]
datos06

       HV014
0          0
1          1
2          1
3          1
4          0
...      ...
37345      0
37346      0
37347      1
37348      0
37349      0

[37350 rows x 1 columns]

In [12]:
datos07 = datos['HV014']
datos07

0        0
1        1
2        1
3        1
4        0
        ..
37345    0
37346    0
37347    1
37348    0
37349    0
Name: HV014, Length: 37350, dtype: int64

In [13]:
datos06.equals(datos07)

False

In [14]:
type(datos06)

pandas.core.frame.DataFrame

In [15]:
type(datos07)

pandas.core.series.Series

## Renombrar variables

In [17]:
# Para conocer el nombre de las columnas
datos01.columns

Index(['HV009', 'HV010', 'HV014', 'HV015', 'HV024', 'HV025', 'HV035', 'HV042',
       'NOMCCPP', 'LONGITUDX', 'LATITUDY'],
      dtype='object')

In [18]:
# Manera 1 de renombrar: Especificar una nueva lista de nombres de columnas, previa copia
datos08 = datos01.copy()
datos08.columns = ['TOTAL_HOGAR', 'TOTAL_MUJERES', 'TOTAL_NINOS', 'ENTREVISTA',
                   'DEPARTAMENTO', 'AREA', 'NINOS_ELEG', 'HEMOG_ELEG', 'NOMCCPP',
                   'LONGITUDX', 'LATITUDY']
# debemos indicar la cantidad total de nombres

In [19]:
# Manera 2 de renombrar: usando .rename (no necesita .copy), especificando un diccionario
# con nombre_antiguo : nombre_nuevo
datos09 = datos01.rename(columns={'HV009': 'TOTAL_HOGAR',
                                  'HV010': 'TOTAL_MUJERES',
                                  'HV014': 'TOTAL_NINOS',
                                  'HV015': 'ENTREVISTA',
                                  'HV024': 'DEPARTAMENTO',
                                  'HV025': 'AREA',
                                  'HV035': 'NINOS_ELEG',
                                  'HV042': 'HEMOG_ELEG'})
# no es necesario indicar todos los nombres

In [20]:
datos08.equals(datos09)

True

In [21]:
datos08

,TOTAL_HOGAR,TOTAL_MUJERES,TOTAL_NINOS,ENTREVISTA,DEPARTAMENTO,AREA,NINOS_ELEG,HEMOG_ELEG,NOMCCPP,LONGITUDX,LATITUDY
0,4,0,0,1,1,1,0,1,CHACHAPOYAS,-77.874030,-6.221249
1,3,1,1,1,1,1,1,1,CHACHAPOYAS,-77.874030,-6.221249
2,5,3,1,1,1,1,1,1,CHACHAPOYAS,-77.874030,-6.221249
3,4,2,1,1,1,1,1,1,CHACHAPOYAS,-77.874030,-6.221249
4,2,0,0,1,1,1,0,1,CHACHAPOYAS,-77.874030,-6.221249
...,...,...,...,...,...,...,...,...,...,...,...
37345,0,0,0,5,15,1,0,1,SAN MIGUEL,-77.079472,-12.090833
37346,0,0,0,5,15,1,0,1,SAN MIGUEL,-77.079472,-12.090833
37347,3,1,1,1,15,1,1,1,SAN MIGUEL,-77.079472,-12.090833
37348,0,0,0,5,15,1,0,1,SAN MIGUEL,-77.079472,-12.090833
37349,0,0,0,5,15,1,0,1,SAN MIGUEL,-77.079472,-12.090833

## Creación de variables

In [24]:
# Creamos variable a variable o columna a columna
datos10 = datos08.copy()
datos10['TOTAL_MUJ_NIN'] = datos10['TOTAL_MUJERES'] + datos10['TOTAL_NINOS']
datos10['TOTAL_OTROS']   = datos10['TOTAL_HOGAR'] - datos10['TOTAL_MUJ_NIN']

In [22]:
# Creamos las variables con assign (similar al mutate de R)
datos11 = datos08.copy().assign(
    TOTAL_MUJ_NIN = lambda w: w['TOTAL_MUJERES'] + w['TOTAL_NINOS'],
    TOTAL_OTROS   = lambda x: x['TOTAL_HOGAR'] - x['TOTAL_MUJ_NIN'])

In [25]:
datos10.equals(datos11)

True

In [26]:
datos11

,TOTAL_HOGAR,TOTAL_MUJERES,TOTAL_NINOS,ENTREVISTA,DEPARTAMENTO,AREA,NINOS_ELEG,HEMOG_ELEG,NOMCCPP,LONGITUDX,LATITUDY,TOTAL_MUJ_NIN,TOTAL_OTROS
0,4,0,0,1,1,1,0,1,CHACHAPOYAS,-77.874030,-6.221249,0,4
1,3,1,1,1,1,1,1,1,CHACHAPOYAS,-77.874030,-6.221249,2,1
2,5,3,1,1,1,1,1,1,CHACHAPOYAS,-77.874030,-6.221249,4,1
3,4,2,1,1,1,1,1,1,CHACHAPOYAS,-77.874030,-6.221249,3,1
4,2,0,0,1,1,1,0,1,CHACHAPOYAS,-77.874030,-6.221249,0,2
...,...,...,...,...,...,...,...,...,...,...,...,...,...
37345,0,0,0,5,15,1,0,1,SAN MIGUEL,-77.079472,-12.090833,0,0
37346,0,0,0,5,15,1,0,1,SAN MIGUEL,-77.079472,-12.090833,0,0
37347,3,1,1,1,15,1,1,1,SAN MIGUEL,-77.079472,-12.090833,2,1
37348,0,0,0,5,15,1,0,1,SAN MIGUEL,-77.079472,-12.090833,0,0
37349,0,0,0,5,15,1,0,1,SAN MIGUEL,-77.079472,-12.090833,0,0

Otro ejemplo:

In [27]:
import numpy as np
datos11 = datos08.copy()
datos11['LIMA'] = np.where(datos11['DEPARTAMENTO'] == "LIMA", "SI", "NO")

In [28]:
datos12 = datos08.copy().assign(
    LIMA = lambda x: x['DEPARTAMENTO'].apply(lambda y: "SI" if y == "LIMA" else "NO"))

In [29]:
datos11.equals(datos12)

True

datos11['DEPARTAMENTO'] == "LIMA" es para comparar con un solo valor

datos13['DEPARTAMENTO'].isin(["LIMA", "CALLAO"]) es para comparar con más de un valor

In [31]:
datos13 = datos08.copy()
datos13['LIMA_CALLAO'] = np.where(datos13['DEPARTAMENTO'].isin(["LIMA", "CALLAO"]), "SI", "NO")

In [32]:
datos14 = datos08.copy().assign(
    LIMA_CALLAO = lambda x: x['DEPARTAMENTO'].apply(lambda y: "SI" if y in ["LIMA", "CALLAO"] else "NO"))

In [33]:
datos13.equals(datos14)

True

In [34]:
datos15 = datos08.copy()
datos15['TOTAL_MUJ_NIN'] = datos15['TOTAL_MUJERES'] + datos15['TOTAL_NINOS']
datos15['TOTAL_OTROS']   = datos15['TOTAL_HOGAR'] - datos15['TOTAL_MUJ_NIN']
datos15['LIMA']          = np.where(datos15['DEPARTAMENTO'] == "LIMA", "SI", "NO")
datos15['LIMA_CALLAO']   = np.where(datos15['DEPARTAMENTO'].isin(["LIMA", "CALLAO"]), "SI", "NO")

In [35]:
datos16 = datos08.copy().assign(
    TOTAL_MUJ_NIN = lambda x: x['TOTAL_MUJERES'] + x['TOTAL_NINOS'],
    TOTAL_OTROS   = lambda x: x['TOTAL_HOGAR'] - x['TOTAL_MUJ_NIN'],
    LIMA          = lambda x: x['DEPARTAMENTO'].apply(lambda y: "SI" if y == "LIMA" else "NO"),
    LIMA_CALLAO   = lambda x: x['DEPARTAMENTO'].apply(lambda y: "SI" if y in ["LIMA", "CALLAO"] else "NO"))

In [36]:
datos15.equals(datos16)

True

In [39]:
datos16

,TOTAL_HOGAR,TOTAL_MUJERES,TOTAL_NINOS,ENTREVISTA,DEPARTAMENTO,AREA,NINOS_ELEG,HEMOG_ELEG,NOMCCPP,LONGITUDX,LATITUDY,TOTAL_MUJ_NIN,TOTAL_OTROS,LIMA,LIMA_CALLAO
0,4,0,0,1,1,1,0,1,CHACHAPOYAS,-77.874030,-6.221249,0,4,NO,NO
1,3,1,1,1,1,1,1,1,CHACHAPOYAS,-77.874030,-6.221249,2,1,NO,NO
2,5,3,1,1,1,1,1,1,CHACHAPOYAS,-77.874030,-6.221249,4,1,NO,NO
3,4,2,1,1,1,1,1,1,CHACHAPOYAS,-77.874030,-6.221249,3,1,NO,NO
4,2,0,0,1,1,1,0,1,CHACHAPOYAS,-77.874030,-6.221249,0,2,NO,NO
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
37345,0,0,0,5,15,1,0,1,SAN MIGUEL,-77.079472,-12.090833,0,0,NO,NO
37346,0,0,0,5,15,1,0,1,SAN MIGUEL,-77.079472,-12.090833,0,0,NO,NO
37347,3,1,1,1,15,1,1,1,SAN MIGUEL,-77.079472,-12.090833,2,1,NO,NO
37348,0,0,0,5,15,1,0,1,SAN MIGUEL,-77.079472,-12.090833,0,0,NO,NO
37349,0,0,0,5,15,1,0,1,SAN MIGUEL,-77.079472,-12.090833,0,0,NO,NO

## Modificación de variables

In [38]:
datos16['AREA']

0        1
1        1
2        1
3        1
4        1
        ..
37345    1
37346    1
37347    1
37348    1
37349    1
Name: AREA, Length: 37350, dtype: int64

In [37]:
datos16['AREA'].dtype

dtype('int64')

In [40]:
datos17 = datos16.copy()
datos17['AREA'] = np.where(datos17['AREA'] == 1, "URBANO", "RURAL")

In [41]:
datos18 = datos16.copy().assign(
    AREA = lambda x: x['AREA'].apply(lambda y: "URBANO" if y == 1 else "RURAL"))

In [42]:
datos17['AREA'].dtype # tipo O (Object)

dtype('O')

In [43]:
datos18['AREA'].dtype

dtype('O')

In [44]:
datos18

,TOTAL_HOGAR,TOTAL_MUJERES,TOTAL_NINOS,ENTREVISTA,DEPARTAMENTO,AREA,NINOS_ELEG,HEMOG_ELEG,NOMCCPP,LONGITUDX,LATITUDY,TOTAL_MUJ_NIN,TOTAL_OTROS,LIMA,LIMA_CALLAO
0,4,0,0,1,1,URBANO,0,1,CHACHAPOYAS,-77.874030,-6.221249,0,4,NO,NO
1,3,1,1,1,1,URBANO,1,1,CHACHAPOYAS,-77.874030,-6.221249,2,1,NO,NO
2,5,3,1,1,1,URBANO,1,1,CHACHAPOYAS,-77.874030,-6.221249,4,1,NO,NO
3,4,2,1,1,1,URBANO,1,1,CHACHAPOYAS,-77.874030,-6.221249,3,1,NO,NO
4,2,0,0,1,1,URBANO,0,1,CHACHAPOYAS,-77.874030,-6.221249,0,2,NO,NO
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
37345,0,0,0,5,15,URBANO,0,1,SAN MIGUEL,-77.079472,-12.090833,0,0,NO,NO
37346,0,0,0,5,15,URBANO,0,1,SAN MIGUEL,-77.079472,-12.090833,0,0,NO,NO
37347,3,1,1,1,15,URBANO,1,1,SAN MIGUEL,-77.079472,-12.090833,2,1,NO,NO
37348,0,0,0,5,15,URBANO,0,1,SAN MIGUEL,-77.079472,-12.090833,0,0,NO,NO
37349,0,0,0,5,15,URBANO,0,1,SAN MIGUEL,-77.079472,-12.090833,0,0,NO,NO

## Filtros

In [50]:
# Manera 1 de filtrar: colocando la condición dentro de corchetes
datos19 = datos18[datos18['AREA'] == "URBANO"]
datos19.head()

,TOTAL_HOGAR,TOTAL_MUJERES,TOTAL_NINOS,ENTREVISTA,DEPARTAMENTO,AREA,NINOS_ELEG,HEMOG_ELEG,NOMCCPP,LONGITUDX,LATITUDY,TOTAL_MUJ_NIN,TOTAL_OTROS,LIMA,LIMA_CALLAO
0,4,0,0,1,1,URBANO,0,1,CHACHAPOYAS,-77.87403,-6.221249,0,4,NO,NO
1,3,1,1,1,1,URBANO,1,1,CHACHAPOYAS,-77.87403,-6.221249,2,1,NO,NO
2,5,3,1,1,1,URBANO,1,1,CHACHAPOYAS,-77.87403,-6.221249,4,1,NO,NO
3,4,2,1,1,1,URBANO,1,1,CHACHAPOYAS,-77.87403,-6.221249,3,1,NO,NO
4,2,0,0,1,1,URBANO,0,1,CHACHAPOYAS,-77.87403,-6.221249,0,2,NO,NO

In [51]:
# Manera 2 de filtrar: colocando la condición (entre comillas) en el método query, previa copia
datos20 = datos18.copy().query('AREA == "URBANO"') # query = consulta
datos20.head()

,TOTAL_HOGAR,TOTAL_MUJERES,TOTAL_NINOS,ENTREVISTA,DEPARTAMENTO,AREA,NINOS_ELEG,HEMOG_ELEG,NOMCCPP,LONGITUDX,LATITUDY,TOTAL_MUJ_NIN,TOTAL_OTROS,LIMA,LIMA_CALLAO
0,4,0,0,1,1,URBANO,0,1,CHACHAPOYAS,-77.87403,-6.221249,0,4,NO,NO
1,3,1,1,1,1,URBANO,1,1,CHACHAPOYAS,-77.87403,-6.221249,2,1,NO,NO
2,5,3,1,1,1,URBANO,1,1,CHACHAPOYAS,-77.87403,-6.221249,4,1,NO,NO
3,4,2,1,1,1,URBANO,1,1,CHACHAPOYAS,-77.87403,-6.221249,3,1,NO,NO
4,2,0,0,1,1,URBANO,0,1,CHACHAPOYAS,-77.87403,-6.221249,0,2,NO,NO

In [52]:
datos19.equals(datos20)

True

Otro ejemplo:

In [56]:
# Manera 1 (y: &)
condicion = (datos18['AREA'] == "URBANO") & (datos12['DEPARTAMENTO'] == 4) # devuelve True / False
datos21 = datos18[condicion] # solo selecciona los True
datos21.head()

,TOTAL_HOGAR,TOTAL_MUJERES,TOTAL_NINOS,ENTREVISTA,DEPARTAMENTO,AREA,NINOS_ELEG,HEMOG_ELEG,NOMCCPP,LONGITUDX,LATITUDY,TOTAL_MUJ_NIN,TOTAL_OTROS,LIMA,LIMA_CALLAO
1400,8,3,1,1,4,URBANO,0,1,LA LIBERTAD,-71.568292,-16.402229,4,4,NO,NO
1401,3,1,0,1,4,URBANO,0,1,LA LIBERTAD,-71.568292,-16.402229,1,2,NO,NO
1402,0,0,0,3,4,URBANO,0,1,LA LIBERTAD,-71.568292,-16.402229,0,0,NO,NO
1403,2,1,0,1,4,URBANO,0,1,LA LIBERTAD,-71.568292,-16.402229,1,1,NO,NO
1404,5,1,1,1,4,URBANO,1,1,LA LIBERTAD,-71.568292,-16.402229,2,3,NO,NO

In [59]:
# Manera 2 (y: &, and)
datos22 = datos18.copy().query('AREA == "URBANO" and DEPARTAMENTO == 4')
datos22.info()

<class 'pandas.core.frame.DataFrame'>
Index: 1142 entries, 1400 to 31944
Data columns (total 15 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   TOTAL_HOGAR    1142 non-null   int64
 1   TOTAL_MUJERES  1142 non-null   int64
 2   TOTAL_NINOS    1142 non-null   int64
 3   ENTREVISTA     1142 non-null   int64
 4   DEPARTAMENTO   1142 non-null   int64
 5   AREA           1142 non-null   object
 6   NINOS_ELEG     1142 non-null   int64
 7   HEMOG_ELEG     1142 non-null   int64
 8   NOMCCPP        1142 non-null   object
 9   LONGITUDX      1142 non-null   float64
 10  LATITUDY       1142 non-null   float64
 11  TOTAL_MUJ_NIN  1142 non-null   int64
 12  TOTAL_OTROS    1142 non-null   int64
 13  LIMA           1142 non-null   object
 14  LIMA_CALLAO    1142 non-null   object
dtypes: float64(2), int64(9), object(4)
memory usage: 142.8+ KB

In [60]:
datos22.equals(datos21)

True

Otro ejemplo, con o:

In [63]:
# Manera 1 (o: |) Alt + 124
datos23 = datos18[(datos18['AREA'] == "URBANO") | (datos18['DEPARTAMENTO'] == 4)]
datos23.head()

,TOTAL_HOGAR,TOTAL_MUJERES,TOTAL_NINOS,ENTREVISTA,DEPARTAMENTO,AREA,NINOS_ELEG,HEMOG_ELEG,NOMCCPP,LONGITUDX,LATITUDY,TOTAL_MUJ_NIN,TOTAL_OTROS,LIMA,LIMA_CALLAO
0,4,0,0,1,1,URBANO,0,1,CHACHAPOYAS,-77.87403,-6.221249,0,4,NO,NO
1,3,1,1,1,1,URBANO,1,1,CHACHAPOYAS,-77.87403,-6.221249,2,1,NO,NO
2,5,3,1,1,1,URBANO,1,1,CHACHAPOYAS,-77.87403,-6.221249,4,1,NO,NO
3,4,2,1,1,1,URBANO,1,1,CHACHAPOYAS,-77.87403,-6.221249,3,1,NO,NO
4,2,0,0,1,1,URBANO,0,1,CHACHAPOYAS,-77.87403,-6.221249,0,2,NO,NO

In [64]:
# Manera 2 (o: |, or)
datos24 = datos18.copy().query('AREA == "URBANO" or DEPARTAMENTO == 4')
datos24.head()

,TOTAL_HOGAR,TOTAL_MUJERES,TOTAL_NINOS,ENTREVISTA,DEPARTAMENTO,AREA,NINOS_ELEG,HEMOG_ELEG,NOMCCPP,LONGITUDX,LATITUDY,TOTAL_MUJ_NIN,TOTAL_OTROS,LIMA,LIMA_CALLAO
0,4,0,0,1,1,URBANO,0,1,CHACHAPOYAS,-77.87403,-6.221249,0,4,NO,NO
1,3,1,1,1,1,URBANO,1,1,CHACHAPOYAS,-77.87403,-6.221249,2,1,NO,NO
2,5,3,1,1,1,URBANO,1,1,CHACHAPOYAS,-77.87403,-6.221249,4,1,NO,NO
3,4,2,1,1,1,URBANO,1,1,CHACHAPOYAS,-77.87403,-6.221249,3,1,NO,NO
4,2,0,0,1,1,URBANO,0,1,CHACHAPOYAS,-77.87403,-6.221249,0,2,NO,NO

In [65]:
datos23.equals(datos24)

True

Otro ejemplo:

In [66]:
datos25 = datos18[(datos18['AREA'] == "URBANO") & (datos18['DEPARTAMENTO'].isin([16, 17, 25]))] #16:loreto, 17:madre de dios, 25:ucayali
datos25.head()

,TOTAL_HOGAR,TOTAL_MUJERES,TOTAL_NINOS,ENTREVISTA,DEPARTAMENTO,AREA,NINOS_ELEG,HEMOG_ELEG,NOMCCPP,LONGITUDX,LATITUDY,TOTAL_MUJ_NIN,TOTAL_OTROS,LIMA,LIMA_CALLAO
8057,5,1,1,1,16,URBANO,1,1,PUNCHANA,-73.248018,-3.728792,2,3,NO,NO
8058,5,1,1,1,16,URBANO,1,1,PUNCHANA,-73.248018,-3.728792,2,3,NO,NO
8059,3,1,0,1,16,URBANO,0,1,PUNCHANA,-73.248018,-3.728792,1,2,NO,NO
8060,3,0,0,1,16,URBANO,0,1,PUNCHANA,-73.248018,-3.728792,0,3,NO,NO
8061,4,2,1,1,16,URBANO,0,1,PUNCHANA,-73.248018,-3.728792,3,1,NO,NO

In [67]:
datos26 = datos18.copy().query('AREA == "URBANO" and DEPARTAMENTO in [16, 17, 25]')
datos26.head()

,TOTAL_HOGAR,TOTAL_MUJERES,TOTAL_NINOS,ENTREVISTA,DEPARTAMENTO,AREA,NINOS_ELEG,HEMOG_ELEG,NOMCCPP,LONGITUDX,LATITUDY,TOTAL_MUJ_NIN,TOTAL_OTROS,LIMA,LIMA_CALLAO
8057,5,1,1,1,16,URBANO,1,1,PUNCHANA,-73.248018,-3.728792,2,3,NO,NO
8058,5,1,1,1,16,URBANO,1,1,PUNCHANA,-73.248018,-3.728792,2,3,NO,NO
8059,3,1,0,1,16,URBANO,0,1,PUNCHANA,-73.248018,-3.728792,1,2,NO,NO
8060,3,0,0,1,16,URBANO,0,1,PUNCHANA,-73.248018,-3.728792,0,3,NO,NO
8061,4,2,1,1,16,URBANO,0,1,PUNCHANA,-73.248018,-3.728792,3,1,NO,NO

In [68]:
datos25.equals(datos26)

True

Un último ejemplo:

In [69]:
datos27 = datos18[datos18['DEPARTAMENTO'] != 12] # != es diferente
datos27.head()

,TOTAL_HOGAR,TOTAL_MUJERES,TOTAL_NINOS,ENTREVISTA,DEPARTAMENTO,AREA,NINOS_ELEG,HEMOG_ELEG,NOMCCPP,LONGITUDX,LATITUDY,TOTAL_MUJ_NIN,TOTAL_OTROS,LIMA,LIMA_CALLAO
0,4,0,0,1,1,URBANO,0,1,CHACHAPOYAS,-77.87403,-6.221249,0,4,NO,NO
1,3,1,1,1,1,URBANO,1,1,CHACHAPOYAS,-77.87403,-6.221249,2,1,NO,NO
2,5,3,1,1,1,URBANO,1,1,CHACHAPOYAS,-77.87403,-6.221249,4,1,NO,NO
3,4,2,1,1,1,URBANO,1,1,CHACHAPOYAS,-77.87403,-6.221249,3,1,NO,NO
4,2,0,0,1,1,URBANO,0,1,CHACHAPOYAS,-77.87403,-6.221249,0,2,NO,NO

In [70]:
datos29 = datos18[~(datos18['DEPARTAMENTO'] == 12)] # ~(condición) niega dicha condición
datos29.head()

,TOTAL_HOGAR,TOTAL_MUJERES,TOTAL_NINOS,ENTREVISTA,DEPARTAMENTO,AREA,NINOS_ELEG,HEMOG_ELEG,NOMCCPP,LONGITUDX,LATITUDY,TOTAL_MUJ_NIN,TOTAL_OTROS,LIMA,LIMA_CALLAO
0,4,0,0,1,1,URBANO,0,1,CHACHAPOYAS,-77.87403,-6.221249,0,4,NO,NO
1,3,1,1,1,1,URBANO,1,1,CHACHAPOYAS,-77.87403,-6.221249,2,1,NO,NO
2,5,3,1,1,1,URBANO,1,1,CHACHAPOYAS,-77.87403,-6.221249,4,1,NO,NO
3,4,2,1,1,1,URBANO,1,1,CHACHAPOYAS,-77.87403,-6.221249,3,1,NO,NO
4,2,0,0,1,1,URBANO,0,1,CHACHAPOYAS,-77.87403,-6.221249,0,2,NO,NO

In [71]:
datos28 = datos18.copy().query('DEPARTAMENTO != 12')
datos28.head()

,TOTAL_HOGAR,TOTAL_MUJERES,TOTAL_NINOS,ENTREVISTA,DEPARTAMENTO,AREA,NINOS_ELEG,HEMOG_ELEG,NOMCCPP,LONGITUDX,LATITUDY,TOTAL_MUJ_NIN,TOTAL_OTROS,LIMA,LIMA_CALLAO
0,4,0,0,1,1,URBANO,0,1,CHACHAPOYAS,-77.87403,-6.221249,0,4,NO,NO
1,3,1,1,1,1,URBANO,1,1,CHACHAPOYAS,-77.87403,-6.221249,2,1,NO,NO
2,5,3,1,1,1,URBANO,1,1,CHACHAPOYAS,-77.87403,-6.221249,4,1,NO,NO
3,4,2,1,1,1,URBANO,1,1,CHACHAPOYAS,-77.87403,-6.221249,3,1,NO,NO
4,2,0,0,1,1,URBANO,0,1,CHACHAPOYAS,-77.87403,-6.221249,0,2,NO,NO

In [74]:
datos29.equals(datos28)

True